version: "3.9"

services:
  frontend:
    build: ./frontend
    image: food-delivery-frontend
    ports:
      - "5173:5173"

  backend:
    build: ./backend
    image: food-delivery-backend
    ports:
      - "4000:4000"

  admin:
    build: ./admin
    image: food-delivery-admin
    ports:
      - "5174:5174"

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"


